name: "Generator"

on:
  workflow_dispatch:
    inputs:
      LANG:
        type: choice
        description: "generate golang(go-mod/vendor) or javascript(node_modules) deps"
        options:
          - golang
          - javascript
          - javascript(pnpm)
          - rust
          - dart
      REPO:
        description: "(optional) github repo name: torvalds/linux"
      SOURCE_URL:
        description: "(optional) git clone url for non-GitHub platforms, e.g. https://github.com/torvalds/linux.git"
      TAG:
        description: "git tag: v6.19"
        required: true
      P:
        description: "P in ebuild: gentoo-kernel-6.19"
        required: true
      WORKDIR:
        description: "(optional) source directory to perform scripts"
        default: ""
      VENDORDIR:
        description: "(optional) golang vendor.tar.xz, input S in ebuild"
        default: ""

jobs:
  generator:
    uses: ./.github/workflows/_generator_reusable.yml
    with:
      LANG: ${{ inputs.LANG }}
      REPO: ${{ inputs.REPO }}
      SOURCE_URL: ${{ inputs.SOURCE_URL }}
      TAG: ${{ inputs.TAG }}
      P: ${{ inputs.P }}
      WORKDIR: ${{ inputs.WORKDIR }}
      VENDORDIR: ${{ inputs.VENDORDIR }}
